CREATE TABLE user_roles (
    role_id char(1) NOT NULL,
    description varchar NOT NULL,
    PRIMARY KEY (role_id)
);

CREATE TABLE users (
    user_id int GENERATED BY DEFAULT AS IDENTITY,
    role_id char(1) NOT NULL,
    uid varchar NOT NULL,
    email varchar NOT NULL,

    PRIMARY KEY (user_id),
    CONSTRAINT fk_role
        FOREIGN KEY (role_id)
            REFERENCES user_roles(role_id)
);

CREATE TABLE session (
    sid varchar NOT NULL COLLATE "default",
    sess json NOT NULL,
    expire timestamp(6) NOT NULL,

    PRIMARY KEY (sid) NOT DEFERRABLE INITIALLY IMMEDIATE
) WITH (OIDS=FALSE);

CREATE INDEX "IDX_session_expire" ON "session" ("expire");