CREATE TABLE user_roles
(
    role_id     char(1) NOT NULL,
    description varchar NOT NULL,
    PRIMARY KEY (role_id)
);

CREATE TABLE users
(
    user_id int GENERATED BY DEFAULT AS IDENTITY,
    role_id char(1) NOT NULL,
    uid     varchar,
    email   varchar NOT NULL,
    name    varchar NOT NULL,


    PRIMARY KEY (user_id),
    CONSTRAINT fk_role
        FOREIGN KEY (role_id)
            REFERENCES user_roles (role_id)
);

CREATE TABLE session
(
    sid    varchar      NOT NULL COLLATE "default",
    sess   json         NOT NULL,
    expire timestamp(6) NOT NULL,

    PRIMARY KEY (sid) NOT DEFERRABLE INITIALLY IMMEDIATE
) WITH (OIDS= FALSE);

CREATE INDEX "IDX_session_expire" ON "session" ("expire");

CREATE TABLE maps
(
    map_id          int GENERATED BY DEFAULT AS IDENTITY,
    user_id         int         NOT NULL,
    center_location point,
    name            varchar(40) NOT NULL,

    PRIMARY KEY (map_id),
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id)
);

CREATE TABLE marker_categories
(
    category_id int GENERATED BY DEFAULT AS IDENTITY,
    description varchar NOT NULL,

    PRIMARY KEY (category_id)
);

CREATE TABLE marker_subcategories
(
    subcategory_id int GENERATED BY DEFAULT AS IDENTITY,
    category_id    int          NOT NULL,
    description    varchar(120) NOT NULL,

    PRIMARY KEY (subcategory_id),
    CONSTRAINT fk_category
        FOREIGN KEY (category_id)
            REFERENCES marker_categories (category_id)

);

CREATE TABLE report_status
(
    report_status_id char(1) NOT NULL,
    description      varchar NOT NULL,

    PRIMARY KEY (report_status_id)
);

CREATE TABLE reports
(
    report_id        int GENERATED BY DEFAULT AS IDENTITY,
    user_id          int     NOT NULL,
    map_id           int     NOT NULL,
    subcategory_id   int     NOT NULL,
    report_status_id char(1) NOT NULL,
    location         point   NOT NULL,
    note             varchar(120),

    PRIMARY KEY (report_id),
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id),
    CONSTRAINT fk_map
        FOREIGN KEY (map_id)
            REFERENCES maps (map_id),
    CONSTRAINT fk_subcategory
        FOREIGN KEY (subcategory_id)
            REFERENCES marker_subcategories (subcategory_id),
    CONSTRAINT fk_report_status
        FOREIGN KEY (report_status_id)
            REFERENCES report_status (report_status_id)
);

CREATE TABLE markers
(
    marker_id      int GENERATED BY DEFAULT AS IDENTITY,
    map_id         int   NOT NULL,
    subcategory_id int   NOT NULL,
    location       point NOT NULL,

    PRIMARY KEY (marker_id),
    CONSTRAINT fk_map
        FOREIGN KEY (map_id)
            REFERENCES maps (map_id),
    CONSTRAINT fk_subcategory
        FOREIGN KEY (subcategory_id)
            REFERENCES marker_subcategories (subcategory_id)
);